apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-workloads
spec:
  generators:
  - list:
      elements:
      - namespace: kube-system
        helmRepo: https://emberstack.github.io/helm-charts
        appName: reflector
        helmTargetRev: 7.1.216
        valueBranch: main
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/danmanners/homelab-kube-cluster.git
        targetRevision: '{{valueBranch}}'
        ref: values
      - repoURL: '{{helmRepo}}'
        chart: '{{appName}}'
        targetRevision: '{{helmTargetRev}}'
        helm:
          valueFiles:
          - '$values/manifests/workloads/{{appName}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
