apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-applicationset
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    repoURL: "https://github.com/danmanners/homelab-kube-cluster.git"
    path: manifests/workloads
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
